/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StationeryRouteImport } from './routes/stationery'
import { Route as StampsRouteImport } from './routes/stamps'
import { Route as SignsPostersRouteImport } from './routes/signs-posters'
import { Route as QrCodeGeneratorRouteImport } from './routes/qr-code-generator'
import { Route as PhotoGiftsRouteImport } from './routes/photo-gifts'
import { Route as PensRouteImport } from './routes/pens'
import { Route as LogomakerRouteImport } from './routes/logomaker'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabelsStickersRouteImport } from './routes/labels-stickers'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DrinkwareRouteImport } from './routes/drinkware'
import { Route as DesignServicesRouteImport } from './routes/design-services'
import { Route as ClothingBagsRouteImport } from './routes/clothing-bags'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BusinessCardsRouteImport } from './routes/business-cards'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSportsJerseysRouteImport } from './routes/services.sports-jerseys'
import { Route as ServicesSchoolCollegeTshirtsRouteImport } from './routes/services.school-college-tshirts'
import { Route as ServicesRoundNeckTshirtsRouteImport } from './routes/services.round-neck-tshirts'
import { Route as ServicesPoloTshirtsRouteImport } from './routes/services.polo-tshirts'
import { Route as ServicesOversizedTshirtsRouteImport } from './routes/services.oversized-tshirts'
import { Route as ServicesEventTshirtsRouteImport } from './routes/services.event-tshirts'
import { Route as ServicesEmbroideryRouteImport } from './routes/services.embroidery'
import { Route as ServicesDtfPrintingRouteImport } from './routes/services.dtf-printing'
import { Route as ServicesCustomTshirtPrintingRouteImport } from './routes/services.custom-tshirt-printing'
import { Route as ServicesCorporateTshirtsRouteImport } from './routes/services.corporate-tshirts'
import { Route as ServicesCompanyUniformTshirtsRouteImport } from './routes/services.company-uniform-tshirts'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as BlogTop10TshirtPrintingHyderabadRouteImport } from './routes/blog.top-10-tshirt-printing-hyderabad'
import { Route as BlogEmbroideryVsDtfPrintingRouteImport } from './routes/blog.embroidery-vs-dtf-printing'
import { Route as BlogCorporateUniformGuideRouteImport } from './routes/blog.corporate-uniform-guide'
import { Route as BlogBulkTshirtPrintingCostRouteImport } from './routes/blog.bulk-tshirt-printing-cost'
import { Route as BlogBestPromotionalTshirtIdeasRouteImport } from './routes/blog.best-promotional-tshirt-ideas'
import { Route as BlogBestFabricCorporateTshirtsRouteImport } from './routes/blog.best-fabric-corporate-tshirts'
import { Route as BlogBestCorporateTshirtPrintingCompanyRouteImport } from './routes/blog.best-corporate-tshirt-printing-company'

const StationeryRoute = StationeryRouteImport.update({
  id: '/stationery',
  path: '/stationery',
  getParentRoute: () => rootRouteImport,
} as any)
const StampsRoute = StampsRouteImport.update({
  id: '/stamps',
  path: '/stamps',
  getParentRoute: () => rootRouteImport,
} as any)
const SignsPostersRoute = SignsPostersRouteImport.update({
  id: '/signs-posters',
  path: '/signs-posters',
  getParentRoute: () => rootRouteImport,
} as any)
const QrCodeGeneratorRoute = QrCodeGeneratorRouteImport.update({
  id: '/qr-code-generator',
  path: '/qr-code-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoGiftsRoute = PhotoGiftsRouteImport.update({
  id: '/photo-gifts',
  path: '/photo-gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const PensRoute = PensRouteImport.update({
  id: '/pens',
  path: '/pens',
  getParentRoute: () => rootRouteImport,
} as any)
const LogomakerRoute = LogomakerRouteImport.update({
  id: '/logomaker',
  path: '/logomaker',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelsStickersRoute = LabelsStickersRouteImport.update({
  id: '/labels-stickers',
  path: '/labels-stickers',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinkwareRoute = DrinkwareRouteImport.update({
  id: '/drinkware',
  path: '/drinkware',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignServicesRoute = DesignServicesRouteImport.update({
  id: '/design-services',
  path: '/design-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ClothingBagsRoute = ClothingBagsRouteImport.update({
  id: '/clothing-bags',
  path: '/clothing-bags',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCardsRoute = BusinessCardsRouteImport.update({
  id: '/business-cards',
  path: '/business-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSportsJerseysRoute = ServicesSportsJerseysRouteImport.update({
  id: '/services/sports-jerseys',
  path: '/services/sports-jerseys',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSchoolCollegeTshirtsRoute =
  ServicesSchoolCollegeTshirtsRouteImport.update({
    id: '/services/school-college-tshirts',
    path: '/services/school-college-tshirts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesRoundNeckTshirtsRoute =
  ServicesRoundNeckTshirtsRouteImport.update({
    id: '/services/round-neck-tshirts',
    path: '/services/round-neck-tshirts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesPoloTshirtsRoute = ServicesPoloTshirtsRouteImport.update({
  id: '/services/polo-tshirts',
  path: '/services/polo-tshirts',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesOversizedTshirtsRoute =
  ServicesOversizedTshirtsRouteImport.update({
    id: '/services/oversized-tshirts',
    path: '/services/oversized-tshirts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesEventTshirtsRoute = ServicesEventTshirtsRouteImport.update({
  id: '/services/event-tshirts',
  path: '/services/event-tshirts',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEmbroideryRoute = ServicesEmbroideryRouteImport.update({
  id: '/services/embroidery',
  path: '/services/embroidery',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDtfPrintingRoute = ServicesDtfPrintingRouteImport.update({
  id: '/services/dtf-printing',
  path: '/services/dtf-printing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCustomTshirtPrintingRoute =
  ServicesCustomTshirtPrintingRouteImport.update({
    id: '/services/custom-tshirt-printing',
    path: '/services/custom-tshirt-printing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCorporateTshirtsRoute =
  ServicesCorporateTshirtsRouteImport.update({
    id: '/services/corporate-tshirts',
    path: '/services/corporate-tshirts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCompanyUniformTshirtsRoute =
  ServicesCompanyUniformTshirtsRouteImport.update({
    id: '/services/company-uniform-tshirts',
    path: '/services/company-uniform-tshirts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTop10TshirtPrintingHyderabadRoute =
  BlogTop10TshirtPrintingHyderabadRouteImport.update({
    id: '/blog/top-10-tshirt-printing-hyderabad',
    path: '/blog/top-10-tshirt-printing-hyderabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogEmbroideryVsDtfPrintingRoute =
  BlogEmbroideryVsDtfPrintingRouteImport.update({
    id: '/blog/embroidery-vs-dtf-printing',
    path: '/blog/embroidery-vs-dtf-printing',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCorporateUniformGuideRoute =
  BlogCorporateUniformGuideRouteImport.update({
    id: '/blog/corporate-uniform-guide',
    path: '/blog/corporate-uniform-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBulkTshirtPrintingCostRoute =
  BlogBulkTshirtPrintingCostRouteImport.update({
    id: '/blog/bulk-tshirt-printing-cost',
    path: '/blog/bulk-tshirt-printing-cost',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBestPromotionalTshirtIdeasRoute =
  BlogBestPromotionalTshirtIdeasRouteImport.update({
    id: '/blog/best-promotional-tshirt-ideas',
    path: '/blog/best-promotional-tshirt-ideas',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBestFabricCorporateTshirtsRoute =
  BlogBestFabricCorporateTshirtsRouteImport.update({
    id: '/blog/best-fabric-corporate-tshirts',
    path: '/blog/best-fabric-corporate-tshirts',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBestCorporateTshirtPrintingCompanyRoute =
  BlogBestCorporateTshirtPrintingCompanyRouteImport.update({
    id: '/blog/best-corporate-tshirt-printing-company',
    path: '/blog/best-corporate-tshirt-printing-company',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/business-cards': typeof BusinessCardsRoute
  '/cart': typeof CartRoute
  '/clothing-bags': typeof ClothingBagsRoute
  '/design-services': typeof DesignServicesRoute
  '/drinkware': typeof DrinkwareRoute
  '/explore': typeof ExploreRoute
  '/labels-stickers': typeof LabelsStickersRoute
  '/login': typeof LoginRoute
  '/logomaker': typeof LogomakerRoute
  '/pens': typeof PensRoute
  '/photo-gifts': typeof PhotoGiftsRoute
  '/qr-code-generator': typeof QrCodeGeneratorRoute
  '/signs-posters': typeof SignsPostersRoute
  '/stamps': typeof StampsRoute
  '/stationery': typeof StationeryRoute
  '/blog/best-corporate-tshirt-printing-company': typeof BlogBestCorporateTshirtPrintingCompanyRoute
  '/blog/best-fabric-corporate-tshirts': typeof BlogBestFabricCorporateTshirtsRoute
  '/blog/best-promotional-tshirt-ideas': typeof BlogBestPromotionalTshirtIdeasRoute
  '/blog/bulk-tshirt-printing-cost': typeof BlogBulkTshirtPrintingCostRoute
  '/blog/corporate-uniform-guide': typeof BlogCorporateUniformGuideRoute
  '/blog/embroidery-vs-dtf-printing': typeof BlogEmbroideryVsDtfPrintingRoute
  '/blog/top-10-tshirt-printing-hyderabad': typeof BlogTop10TshirtPrintingHyderabadRoute
  '/product/$slug': typeof ProductSlugRoute
  '/services/company-uniform-tshirts': typeof ServicesCompanyUniformTshirtsRoute
  '/services/corporate-tshirts': typeof ServicesCorporateTshirtsRoute
  '/services/custom-tshirt-printing': typeof ServicesCustomTshirtPrintingRoute
  '/services/dtf-printing': typeof ServicesDtfPrintingRoute
  '/services/embroidery': typeof ServicesEmbroideryRoute
  '/services/event-tshirts': typeof ServicesEventTshirtsRoute
  '/services/oversized-tshirts': typeof ServicesOversizedTshirtsRoute
  '/services/polo-tshirts': typeof ServicesPoloTshirtsRoute
  '/services/round-neck-tshirts': typeof ServicesRoundNeckTshirtsRoute
  '/services/school-college-tshirts': typeof ServicesSchoolCollegeTshirtsRoute
  '/services/sports-jerseys': typeof ServicesSportsJerseysRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/business-cards': typeof BusinessCardsRoute
  '/cart': typeof CartRoute
  '/clothing-bags': typeof ClothingBagsRoute
  '/design-services': typeof DesignServicesRoute
  '/drinkware': typeof DrinkwareRoute
  '/explore': typeof ExploreRoute
  '/labels-stickers': typeof LabelsStickersRoute
  '/login': typeof LoginRoute
  '/logomaker': typeof LogomakerRoute
  '/pens': typeof PensRoute
  '/photo-gifts': typeof PhotoGiftsRoute
  '/qr-code-generator': typeof QrCodeGeneratorRoute
  '/signs-posters': typeof SignsPostersRoute
  '/stamps': typeof StampsRoute
  '/stationery': typeof StationeryRoute
  '/blog/best-corporate-tshirt-printing-company': typeof BlogBestCorporateTshirtPrintingCompanyRoute
  '/blog/best-fabric-corporate-tshirts': typeof BlogBestFabricCorporateTshirtsRoute
  '/blog/best-promotional-tshirt-ideas': typeof BlogBestPromotionalTshirtIdeasRoute
  '/blog/bulk-tshirt-printing-cost': typeof BlogBulkTshirtPrintingCostRoute
  '/blog/corporate-uniform-guide': typeof BlogCorporateUniformGuideRoute
  '/blog/embroidery-vs-dtf-printing': typeof BlogEmbroideryVsDtfPrintingRoute
  '/blog/top-10-tshirt-printing-hyderabad': typeof BlogTop10TshirtPrintingHyderabadRoute
  '/product/$slug': typeof ProductSlugRoute
  '/services/company-uniform-tshirts': typeof ServicesCompanyUniformTshirtsRoute
  '/services/corporate-tshirts': typeof ServicesCorporateTshirtsRoute
  '/services/custom-tshirt-printing': typeof ServicesCustomTshirtPrintingRoute
  '/services/dtf-printing': typeof ServicesDtfPrintingRoute
  '/services/embroidery': typeof ServicesEmbroideryRoute
  '/services/event-tshirts': typeof ServicesEventTshirtsRoute
  '/services/oversized-tshirts': typeof ServicesOversizedTshirtsRoute
  '/services/polo-tshirts': typeof ServicesPoloTshirtsRoute
  '/services/round-neck-tshirts': typeof ServicesRoundNeckTshirtsRoute
  '/services/school-college-tshirts': typeof ServicesSchoolCollegeTshirtsRoute
  '/services/sports-jerseys': typeof ServicesSportsJerseysRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/business-cards': typeof BusinessCardsRoute
  '/cart': typeof CartRoute
  '/clothing-bags': typeof ClothingBagsRoute
  '/design-services': typeof DesignServicesRoute
  '/drinkware': typeof DrinkwareRoute
  '/explore': typeof ExploreRoute
  '/labels-stickers': typeof LabelsStickersRoute
  '/login': typeof LoginRoute
  '/logomaker': typeof LogomakerRoute
  '/pens': typeof PensRoute
  '/photo-gifts': typeof PhotoGiftsRoute
  '/qr-code-generator': typeof QrCodeGeneratorRoute
  '/signs-posters': typeof SignsPostersRoute
  '/stamps': typeof StampsRoute
  '/stationery': typeof StationeryRoute
  '/blog/best-corporate-tshirt-printing-company': typeof BlogBestCorporateTshirtPrintingCompanyRoute
  '/blog/best-fabric-corporate-tshirts': typeof BlogBestFabricCorporateTshirtsRoute
  '/blog/best-promotional-tshirt-ideas': typeof BlogBestPromotionalTshirtIdeasRoute
  '/blog/bulk-tshirt-printing-cost': typeof BlogBulkTshirtPrintingCostRoute
  '/blog/corporate-uniform-guide': typeof BlogCorporateUniformGuideRoute
  '/blog/embroidery-vs-dtf-printing': typeof BlogEmbroideryVsDtfPrintingRoute
  '/blog/top-10-tshirt-printing-hyderabad': typeof BlogTop10TshirtPrintingHyderabadRoute
  '/product/$slug': typeof ProductSlugRoute
  '/services/company-uniform-tshirts': typeof ServicesCompanyUniformTshirtsRoute
  '/services/corporate-tshirts': typeof ServicesCorporateTshirtsRoute
  '/services/custom-tshirt-printing': typeof ServicesCustomTshirtPrintingRoute
  '/services/dtf-printing': typeof ServicesDtfPrintingRoute
  '/services/embroidery': typeof ServicesEmbroideryRoute
  '/services/event-tshirts': typeof ServicesEventTshirtsRoute
  '/services/oversized-tshirts': typeof ServicesOversizedTshirtsRoute
  '/services/polo-tshirts': typeof ServicesPoloTshirtsRoute
  '/services/round-neck-tshirts': typeof ServicesRoundNeckTshirtsRoute
  '/services/school-college-tshirts': typeof ServicesSchoolCollegeTshirtsRoute
  '/services/sports-jerseys': typeof ServicesSportsJerseysRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/business-cards'
    | '/cart'
    | '/clothing-bags'
    | '/design-services'
    | '/drinkware'
    | '/explore'
    | '/labels-stickers'
    | '/login'
    | '/logomaker'
    | '/pens'
    | '/photo-gifts'
    | '/qr-code-generator'
    | '/signs-posters'
    | '/stamps'
    | '/stationery'
    | '/blog/best-corporate-tshirt-printing-company'
    | '/blog/best-fabric-corporate-tshirts'
    | '/blog/best-promotional-tshirt-ideas'
    | '/blog/bulk-tshirt-printing-cost'
    | '/blog/corporate-uniform-guide'
    | '/blog/embroidery-vs-dtf-printing'
    | '/blog/top-10-tshirt-printing-hyderabad'
    | '/product/$slug'
    | '/services/company-uniform-tshirts'
    | '/services/corporate-tshirts'
    | '/services/custom-tshirt-printing'
    | '/services/dtf-printing'
    | '/services/embroidery'
    | '/services/event-tshirts'
    | '/services/oversized-tshirts'
    | '/services/polo-tshirts'
    | '/services/round-neck-tshirts'
    | '/services/school-college-tshirts'
    | '/services/sports-jerseys'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/business-cards'
    | '/cart'
    | '/clothing-bags'
    | '/design-services'
    | '/drinkware'
    | '/explore'
    | '/labels-stickers'
    | '/login'
    | '/logomaker'
    | '/pens'
    | '/photo-gifts'
    | '/qr-code-generator'
    | '/signs-posters'
    | '/stamps'
    | '/stationery'
    | '/blog/best-corporate-tshirt-printing-company'
    | '/blog/best-fabric-corporate-tshirts'
    | '/blog/best-promotional-tshirt-ideas'
    | '/blog/bulk-tshirt-printing-cost'
    | '/blog/corporate-uniform-guide'
    | '/blog/embroidery-vs-dtf-printing'
    | '/blog/top-10-tshirt-printing-hyderabad'
    | '/product/$slug'
    | '/services/company-uniform-tshirts'
    | '/services/corporate-tshirts'
    | '/services/custom-tshirt-printing'
    | '/services/dtf-printing'
    | '/services/embroidery'
    | '/services/event-tshirts'
    | '/services/oversized-tshirts'
    | '/services/polo-tshirts'
    | '/services/round-neck-tshirts'
    | '/services/school-college-tshirts'
    | '/services/sports-jerseys'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/business-cards'
    | '/cart'
    | '/clothing-bags'
    | '/design-services'
    | '/drinkware'
    | '/explore'
    | '/labels-stickers'
    | '/login'
    | '/logomaker'
    | '/pens'
    | '/photo-gifts'
    | '/qr-code-generator'
    | '/signs-posters'
    | '/stamps'
    | '/stationery'
    | '/blog/best-corporate-tshirt-printing-company'
    | '/blog/best-fabric-corporate-tshirts'
    | '/blog/best-promotional-tshirt-ideas'
    | '/blog/bulk-tshirt-printing-cost'
    | '/blog/corporate-uniform-guide'
    | '/blog/embroidery-vs-dtf-printing'
    | '/blog/top-10-tshirt-printing-hyderabad'
    | '/product/$slug'
    | '/services/company-uniform-tshirts'
    | '/services/corporate-tshirts'
    | '/services/custom-tshirt-printing'
    | '/services/dtf-printing'
    | '/services/embroidery'
    | '/services/event-tshirts'
    | '/services/oversized-tshirts'
    | '/services/polo-tshirts'
    | '/services/round-neck-tshirts'
    | '/services/school-college-tshirts'
    | '/services/sports-jerseys'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BusinessCardsRoute: typeof BusinessCardsRoute
  CartRoute: typeof CartRoute
  ClothingBagsRoute: typeof ClothingBagsRoute
  DesignServicesRoute: typeof DesignServicesRoute
  DrinkwareRoute: typeof DrinkwareRoute
  ExploreRoute: typeof ExploreRoute
  LabelsStickersRoute: typeof LabelsStickersRoute
  LoginRoute: typeof LoginRoute
  LogomakerRoute: typeof LogomakerRoute
  PensRoute: typeof PensRoute
  PhotoGiftsRoute: typeof PhotoGiftsRoute
  QrCodeGeneratorRoute: typeof QrCodeGeneratorRoute
  SignsPostersRoute: typeof SignsPostersRoute
  StampsRoute: typeof StampsRoute
  StationeryRoute: typeof StationeryRoute
  BlogBestCorporateTshirtPrintingCompanyRoute: typeof BlogBestCorporateTshirtPrintingCompanyRoute
  BlogBestFabricCorporateTshirtsRoute: typeof BlogBestFabricCorporateTshirtsRoute
  BlogBestPromotionalTshirtIdeasRoute: typeof BlogBestPromotionalTshirtIdeasRoute
  BlogBulkTshirtPrintingCostRoute: typeof BlogBulkTshirtPrintingCostRoute
  BlogCorporateUniformGuideRoute: typeof BlogCorporateUniformGuideRoute
  BlogEmbroideryVsDtfPrintingRoute: typeof BlogEmbroideryVsDtfPrintingRoute
  BlogTop10TshirtPrintingHyderabadRoute: typeof BlogTop10TshirtPrintingHyderabadRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ServicesCompanyUniformTshirtsRoute: typeof ServicesCompanyUniformTshirtsRoute
  ServicesCorporateTshirtsRoute: typeof ServicesCorporateTshirtsRoute
  ServicesCustomTshirtPrintingRoute: typeof ServicesCustomTshirtPrintingRoute
  ServicesDtfPrintingRoute: typeof ServicesDtfPrintingRoute
  ServicesEmbroideryRoute: typeof ServicesEmbroideryRoute
  ServicesEventTshirtsRoute: typeof ServicesEventTshirtsRoute
  ServicesOversizedTshirtsRoute: typeof ServicesOversizedTshirtsRoute
  ServicesPoloTshirtsRoute: typeof ServicesPoloTshirtsRoute
  ServicesRoundNeckTshirtsRoute: typeof ServicesRoundNeckTshirtsRoute
  ServicesSchoolCollegeTshirtsRoute: typeof ServicesSchoolCollegeTshirtsRoute
  ServicesSportsJerseysRoute: typeof ServicesSportsJerseysRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stationery': {
      id: '/stationery'
      path: '/stationery'
      fullPath: '/stationery'
      preLoaderRoute: typeof StationeryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stamps': {
      id: '/stamps'
      path: '/stamps'
      fullPath: '/stamps'
      preLoaderRoute: typeof StampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signs-posters': {
      id: '/signs-posters'
      path: '/signs-posters'
      fullPath: '/signs-posters'
      preLoaderRoute: typeof SignsPostersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-code-generator': {
      id: '/qr-code-generator'
      path: '/qr-code-generator'
      fullPath: '/qr-code-generator'
      preLoaderRoute: typeof QrCodeGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-gifts': {
      id: '/photo-gifts'
      path: '/photo-gifts'
      fullPath: '/photo-gifts'
      preLoaderRoute: typeof PhotoGiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pens': {
      id: '/pens'
      path: '/pens'
      fullPath: '/pens'
      preLoaderRoute: typeof PensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logomaker': {
      id: '/logomaker'
      path: '/logomaker'
      fullPath: '/logomaker'
      preLoaderRoute: typeof LogomakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labels-stickers': {
      id: '/labels-stickers'
      path: '/labels-stickers'
      fullPath: '/labels-stickers'
      preLoaderRoute: typeof LabelsStickersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinkware': {
      id: '/drinkware'
      path: '/drinkware'
      fullPath: '/drinkware'
      preLoaderRoute: typeof DrinkwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-services': {
      id: '/design-services'
      path: '/design-services'
      fullPath: '/design-services'
      preLoaderRoute: typeof DesignServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clothing-bags': {
      id: '/clothing-bags'
      path: '/clothing-bags'
      fullPath: '/clothing-bags'
      preLoaderRoute: typeof ClothingBagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-cards': {
      id: '/business-cards'
      path: '/business-cards'
      fullPath: '/business-cards'
      preLoaderRoute: typeof BusinessCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/sports-jerseys': {
      id: '/services/sports-jerseys'
      path: '/services/sports-jerseys'
      fullPath: '/services/sports-jerseys'
      preLoaderRoute: typeof ServicesSportsJerseysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/school-college-tshirts': {
      id: '/services/school-college-tshirts'
      path: '/services/school-college-tshirts'
      fullPath: '/services/school-college-tshirts'
      preLoaderRoute: typeof ServicesSchoolCollegeTshirtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/round-neck-tshirts': {
      id: '/services/round-neck-tshirts'
      path: '/services/round-neck-tshirts'
      fullPath: '/services/round-neck-tshirts'
      preLoaderRoute: typeof ServicesRoundNeckTshirtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/polo-tshirts': {
      id: '/services/polo-tshirts'
      path: '/services/polo-tshirts'
      fullPath: '/services/polo-tshirts'
      preLoaderRoute: typeof ServicesPoloTshirtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/oversized-tshirts': {
      id: '/services/oversized-tshirts'
      path: '/services/oversized-tshirts'
      fullPath: '/services/oversized-tshirts'
      preLoaderRoute: typeof ServicesOversizedTshirtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/event-tshirts': {
      id: '/services/event-tshirts'
      path: '/services/event-tshirts'
      fullPath: '/services/event-tshirts'
      preLoaderRoute: typeof ServicesEventTshirtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/embroidery': {
      id: '/services/embroidery'
      path: '/services/embroidery'
      fullPath: '/services/embroidery'
      preLoaderRoute: typeof ServicesEmbroideryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/dtf-printing': {
      id: '/services/dtf-printing'
      path: '/services/dtf-printing'
      fullPath: '/services/dtf-printing'
      preLoaderRoute: typeof ServicesDtfPrintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/custom-tshirt-printing': {
      id: '/services/custom-tshirt-printing'
      path: '/services/custom-tshirt-printing'
      fullPath: '/services/custom-tshirt-printing'
      preLoaderRoute: typeof ServicesCustomTshirtPrintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/corporate-tshirts': {
      id: '/services/corporate-tshirts'
      path: '/services/corporate-tshirts'
      fullPath: '/services/corporate-tshirts'
      preLoaderRoute: typeof ServicesCorporateTshirtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/company-uniform-tshirts': {
      id: '/services/company-uniform-tshirts'
      path: '/services/company-uniform-tshirts'
      fullPath: '/services/company-uniform-tshirts'
      preLoaderRoute: typeof ServicesCompanyUniformTshirtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/top-10-tshirt-printing-hyderabad': {
      id: '/blog/top-10-tshirt-printing-hyderabad'
      path: '/blog/top-10-tshirt-printing-hyderabad'
      fullPath: '/blog/top-10-tshirt-printing-hyderabad'
      preLoaderRoute: typeof BlogTop10TshirtPrintingHyderabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/embroidery-vs-dtf-printing': {
      id: '/blog/embroidery-vs-dtf-printing'
      path: '/blog/embroidery-vs-dtf-printing'
      fullPath: '/blog/embroidery-vs-dtf-printing'
      preLoaderRoute: typeof BlogEmbroideryVsDtfPrintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/corporate-uniform-guide': {
      id: '/blog/corporate-uniform-guide'
      path: '/blog/corporate-uniform-guide'
      fullPath: '/blog/corporate-uniform-guide'
      preLoaderRoute: typeof BlogCorporateUniformGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/bulk-tshirt-printing-cost': {
      id: '/blog/bulk-tshirt-printing-cost'
      path: '/blog/bulk-tshirt-printing-cost'
      fullPath: '/blog/bulk-tshirt-printing-cost'
      preLoaderRoute: typeof BlogBulkTshirtPrintingCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/best-promotional-tshirt-ideas': {
      id: '/blog/best-promotional-tshirt-ideas'
      path: '/blog/best-promotional-tshirt-ideas'
      fullPath: '/blog/best-promotional-tshirt-ideas'
      preLoaderRoute: typeof BlogBestPromotionalTshirtIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/best-fabric-corporate-tshirts': {
      id: '/blog/best-fabric-corporate-tshirts'
      path: '/blog/best-fabric-corporate-tshirts'
      fullPath: '/blog/best-fabric-corporate-tshirts'
      preLoaderRoute: typeof BlogBestFabricCorporateTshirtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/best-corporate-tshirt-printing-company': {
      id: '/blog/best-corporate-tshirt-printing-company'
      path: '/blog/best-corporate-tshirt-printing-company'
      fullPath: '/blog/best-corporate-tshirt-printing-company'
      preLoaderRoute: typeof BlogBestCorporateTshirtPrintingCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BusinessCardsRoute: BusinessCardsRoute,
  CartRoute: CartRoute,
  ClothingBagsRoute: ClothingBagsRoute,
  DesignServicesRoute: DesignServicesRoute,
  DrinkwareRoute: DrinkwareRoute,
  ExploreRoute: ExploreRoute,
  LabelsStickersRoute: LabelsStickersRoute,
  LoginRoute: LoginRoute,
  LogomakerRoute: LogomakerRoute,
  PensRoute: PensRoute,
  PhotoGiftsRoute: PhotoGiftsRoute,
  QrCodeGeneratorRoute: QrCodeGeneratorRoute,
  SignsPostersRoute: SignsPostersRoute,
  StampsRoute: StampsRoute,
  StationeryRoute: StationeryRoute,
  BlogBestCorporateTshirtPrintingCompanyRoute:
    BlogBestCorporateTshirtPrintingCompanyRoute,
  BlogBestFabricCorporateTshirtsRoute: BlogBestFabricCorporateTshirtsRoute,
  BlogBestPromotionalTshirtIdeasRoute: BlogBestPromotionalTshirtIdeasRoute,
  BlogBulkTshirtPrintingCostRoute: BlogBulkTshirtPrintingCostRoute,
  BlogCorporateUniformGuideRoute: BlogCorporateUniformGuideRoute,
  BlogEmbroideryVsDtfPrintingRoute: BlogEmbroideryVsDtfPrintingRoute,
  BlogTop10TshirtPrintingHyderabadRoute: BlogTop10TshirtPrintingHyderabadRoute,
  ProductSlugRoute: ProductSlugRoute,
  ServicesCompanyUniformTshirtsRoute: ServicesCompanyUniformTshirtsRoute,
  ServicesCorporateTshirtsRoute: ServicesCorporateTshirtsRoute,
  ServicesCustomTshirtPrintingRoute: ServicesCustomTshirtPrintingRoute,
  ServicesDtfPrintingRoute: ServicesDtfPrintingRoute,
  ServicesEmbroideryRoute: ServicesEmbroideryRoute,
  ServicesEventTshirtsRoute: ServicesEventTshirtsRoute,
  ServicesOversizedTshirtsRoute: ServicesOversizedTshirtsRoute,
  ServicesPoloTshirtsRoute: ServicesPoloTshirtsRoute,
  ServicesRoundNeckTshirtsRoute: ServicesRoundNeckTshirtsRoute,
  ServicesSchoolCollegeTshirtsRoute: ServicesSchoolCollegeTshirtsRoute,
  ServicesSportsJerseysRoute: ServicesSportsJerseysRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
