/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StationeryRouteImport } from './routes/stationery'
import { Route as StampsRouteImport } from './routes/stamps'
import { Route as SignsPostersRouteImport } from './routes/signs-posters'
import { Route as QrCodeGeneratorRouteImport } from './routes/qr-code-generator'
import { Route as PhotoGiftsRouteImport } from './routes/photo-gifts'
import { Route as PensRouteImport } from './routes/pens'
import { Route as LogomakerRouteImport } from './routes/logomaker'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabelsStickersRouteImport } from './routes/labels-stickers'
import { Route as HelpCentreRouteImport } from './routes/help-centre'
import { Route as DrinkwareRouteImport } from './routes/drinkware'
import { Route as DesignServicesRouteImport } from './routes/design-services'
import { Route as ClothingBagsRouteImport } from './routes/clothing-bags'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BusinessCardsRouteImport } from './routes/business-cards'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const StationeryRoute = StationeryRouteImport.update({
  id: '/stationery',
  path: '/stationery',
  getParentRoute: () => rootRouteImport,
} as any)
const StampsRoute = StampsRouteImport.update({
  id: '/stamps',
  path: '/stamps',
  getParentRoute: () => rootRouteImport,
} as any)
const SignsPostersRoute = SignsPostersRouteImport.update({
  id: '/signs-posters',
  path: '/signs-posters',
  getParentRoute: () => rootRouteImport,
} as any)
const QrCodeGeneratorRoute = QrCodeGeneratorRouteImport.update({
  id: '/qr-code-generator',
  path: '/qr-code-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoGiftsRoute = PhotoGiftsRouteImport.update({
  id: '/photo-gifts',
  path: '/photo-gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const PensRoute = PensRouteImport.update({
  id: '/pens',
  path: '/pens',
  getParentRoute: () => rootRouteImport,
} as any)
const LogomakerRoute = LogomakerRouteImport.update({
  id: '/logomaker',
  path: '/logomaker',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelsStickersRoute = LabelsStickersRouteImport.update({
  id: '/labels-stickers',
  path: '/labels-stickers',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCentreRoute = HelpCentreRouteImport.update({
  id: '/help-centre',
  path: '/help-centre',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinkwareRoute = DrinkwareRouteImport.update({
  id: '/drinkware',
  path: '/drinkware',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignServicesRoute = DesignServicesRouteImport.update({
  id: '/design-services',
  path: '/design-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ClothingBagsRoute = ClothingBagsRouteImport.update({
  id: '/clothing-bags',
  path: '/clothing-bags',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCardsRoute = BusinessCardsRouteImport.update({
  id: '/business-cards',
  path: '/business-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/business-cards': typeof BusinessCardsRoute
  '/cart': typeof CartRoute
  '/clothing-bags': typeof ClothingBagsRoute
  '/design-services': typeof DesignServicesRoute
  '/drinkware': typeof DrinkwareRoute
  '/help-centre': typeof HelpCentreRoute
  '/labels-stickers': typeof LabelsStickersRoute
  '/login': typeof LoginRoute
  '/logomaker': typeof LogomakerRoute
  '/pens': typeof PensRoute
  '/photo-gifts': typeof PhotoGiftsRoute
  '/qr-code-generator': typeof QrCodeGeneratorRoute
  '/signs-posters': typeof SignsPostersRoute
  '/stamps': typeof StampsRoute
  '/stationery': typeof StationeryRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/business-cards': typeof BusinessCardsRoute
  '/cart': typeof CartRoute
  '/clothing-bags': typeof ClothingBagsRoute
  '/design-services': typeof DesignServicesRoute
  '/drinkware': typeof DrinkwareRoute
  '/help-centre': typeof HelpCentreRoute
  '/labels-stickers': typeof LabelsStickersRoute
  '/login': typeof LoginRoute
  '/logomaker': typeof LogomakerRoute
  '/pens': typeof PensRoute
  '/photo-gifts': typeof PhotoGiftsRoute
  '/qr-code-generator': typeof QrCodeGeneratorRoute
  '/signs-posters': typeof SignsPostersRoute
  '/stamps': typeof StampsRoute
  '/stationery': typeof StationeryRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/business-cards': typeof BusinessCardsRoute
  '/cart': typeof CartRoute
  '/clothing-bags': typeof ClothingBagsRoute
  '/design-services': typeof DesignServicesRoute
  '/drinkware': typeof DrinkwareRoute
  '/help-centre': typeof HelpCentreRoute
  '/labels-stickers': typeof LabelsStickersRoute
  '/login': typeof LoginRoute
  '/logomaker': typeof LogomakerRoute
  '/pens': typeof PensRoute
  '/photo-gifts': typeof PhotoGiftsRoute
  '/qr-code-generator': typeof QrCodeGeneratorRoute
  '/signs-posters': typeof SignsPostersRoute
  '/stamps': typeof StampsRoute
  '/stationery': typeof StationeryRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/business-cards'
    | '/cart'
    | '/clothing-bags'
    | '/design-services'
    | '/drinkware'
    | '/help-centre'
    | '/labels-stickers'
    | '/login'
    | '/logomaker'
    | '/pens'
    | '/photo-gifts'
    | '/qr-code-generator'
    | '/signs-posters'
    | '/stamps'
    | '/stationery'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/business-cards'
    | '/cart'
    | '/clothing-bags'
    | '/design-services'
    | '/drinkware'
    | '/help-centre'
    | '/labels-stickers'
    | '/login'
    | '/logomaker'
    | '/pens'
    | '/photo-gifts'
    | '/qr-code-generator'
    | '/signs-posters'
    | '/stamps'
    | '/stationery'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/business-cards'
    | '/cart'
    | '/clothing-bags'
    | '/design-services'
    | '/drinkware'
    | '/help-centre'
    | '/labels-stickers'
    | '/login'
    | '/logomaker'
    | '/pens'
    | '/photo-gifts'
    | '/qr-code-generator'
    | '/signs-posters'
    | '/stamps'
    | '/stationery'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BusinessCardsRoute: typeof BusinessCardsRoute
  CartRoute: typeof CartRoute
  ClothingBagsRoute: typeof ClothingBagsRoute
  DesignServicesRoute: typeof DesignServicesRoute
  DrinkwareRoute: typeof DrinkwareRoute
  HelpCentreRoute: typeof HelpCentreRoute
  LabelsStickersRoute: typeof LabelsStickersRoute
  LoginRoute: typeof LoginRoute
  LogomakerRoute: typeof LogomakerRoute
  PensRoute: typeof PensRoute
  PhotoGiftsRoute: typeof PhotoGiftsRoute
  QrCodeGeneratorRoute: typeof QrCodeGeneratorRoute
  SignsPostersRoute: typeof SignsPostersRoute
  StampsRoute: typeof StampsRoute
  StationeryRoute: typeof StationeryRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stationery': {
      id: '/stationery'
      path: '/stationery'
      fullPath: '/stationery'
      preLoaderRoute: typeof StationeryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stamps': {
      id: '/stamps'
      path: '/stamps'
      fullPath: '/stamps'
      preLoaderRoute: typeof StampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signs-posters': {
      id: '/signs-posters'
      path: '/signs-posters'
      fullPath: '/signs-posters'
      preLoaderRoute: typeof SignsPostersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-code-generator': {
      id: '/qr-code-generator'
      path: '/qr-code-generator'
      fullPath: '/qr-code-generator'
      preLoaderRoute: typeof QrCodeGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-gifts': {
      id: '/photo-gifts'
      path: '/photo-gifts'
      fullPath: '/photo-gifts'
      preLoaderRoute: typeof PhotoGiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pens': {
      id: '/pens'
      path: '/pens'
      fullPath: '/pens'
      preLoaderRoute: typeof PensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logomaker': {
      id: '/logomaker'
      path: '/logomaker'
      fullPath: '/logomaker'
      preLoaderRoute: typeof LogomakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labels-stickers': {
      id: '/labels-stickers'
      path: '/labels-stickers'
      fullPath: '/labels-stickers'
      preLoaderRoute: typeof LabelsStickersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-centre': {
      id: '/help-centre'
      path: '/help-centre'
      fullPath: '/help-centre'
      preLoaderRoute: typeof HelpCentreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinkware': {
      id: '/drinkware'
      path: '/drinkware'
      fullPath: '/drinkware'
      preLoaderRoute: typeof DrinkwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-services': {
      id: '/design-services'
      path: '/design-services'
      fullPath: '/design-services'
      preLoaderRoute: typeof DesignServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clothing-bags': {
      id: '/clothing-bags'
      path: '/clothing-bags'
      fullPath: '/clothing-bags'
      preLoaderRoute: typeof ClothingBagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-cards': {
      id: '/business-cards'
      path: '/business-cards'
      fullPath: '/business-cards'
      preLoaderRoute: typeof BusinessCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BusinessCardsRoute: BusinessCardsRoute,
  CartRoute: CartRoute,
  ClothingBagsRoute: ClothingBagsRoute,
  DesignServicesRoute: DesignServicesRoute,
  DrinkwareRoute: DrinkwareRoute,
  HelpCentreRoute: HelpCentreRoute,
  LabelsStickersRoute: LabelsStickersRoute,
  LoginRoute: LoginRoute,
  LogomakerRoute: LogomakerRoute,
  PensRoute: PensRoute,
  PhotoGiftsRoute: PhotoGiftsRoute,
  QrCodeGeneratorRoute: QrCodeGeneratorRoute,
  SignsPostersRoute: SignsPostersRoute,
  StampsRoute: StampsRoute,
  StationeryRoute: StationeryRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
